# Generated by Django 5.0.6 on 2024-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_item_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
